apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ro5qdeo1g-java-springboot
  janus-idp.io/tekton: ro5qdeo1g-java-springboot
  backstage.io/kubernetes-id: ro5qdeo1g-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ro5qdeo1g-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
